# Generated by Django 4.2.11 on 2024-06-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="punkweb_forms.form",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at",),
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("required", models.BooleanField(default=True)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("help_text", models.TextField(blank=True)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("boolean", "Boolean"),
                            ("char", "Char"),
                            ("choice", "Choice"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("decimal", "Decimal"),
                            ("duration", "Duration"),
                            ("email", "Email"),
                            ("file", "File"),
                            ("filepath", "Filepath"),
                            ("float", "Float"),
                            ("image", "Image"),
                            ("integer", "Integer"),
                            ("multiplechoice", "MultipleChoice"),
                            ("time", "Time"),
                            ("url", "URL"),
                            ("uuid", "UUID"),
                        ],
                        max_length=255,
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="punkweb_forms.form",
                    ),
                ),
            ],
            options={
                "ordering": ("form", "order"),
            },
        ),
    ]
